### ISSUE TITLE
Theivery

### ISSUE THREAD

**Issue by ThomasThings** [ShardedFilms/NeoGenesis#1]
You blatantly stole assets, names, and more from Aureus

**Comment by XenoForce** [comment]
> You blatantly stole assets, names, and more from Aureus

Pffft.

Aureus used to release his work under the GPLv3.

But Aureus foolishly changed his license agreement on  Feb 28, 2022.

So, if you want to grab stuff from Aureus, just make sure you go back in time (before Feb 28, 2022) in the git repository, and then take whatever you want to take.

Also: What is "Theivery"? LOL

**Comment by ThomasThings** [comment]
Aureus changed his license agreement on Feb 28, 2022.

He added the sprites for all of the items (excluding those added later, on December 6, 2022) on August 8, 2022.

The Item sprites, for example, would fall under the new license agreement, which solely states "Dont us my sprites without permission".

ShardedFilms has _all_ of Aureus' item sprites in their repository, added on May 5, 2023, at the **earliest**.

Thievery: the action of stealing another person's property.

ShardedFilms clearly doesn't care that they're being scummy by stealing and rebranding someone else's work, but seriously, how hard can it be to just make your own mod? Aureus has said he is ok with, and even encourages mod addons and such.

**Comment by XenoForce** [comment]
> *Theivery / Thievery: the action of stealing another person's property.*

Regardless of your questionable spelling, your definition does not apply in this case, because Aureus still has his copy of everything. Aureus has not lost anything. Nothing was taken from him.

BTW: who are you anyway, to be complaining about this? Shouldn't Aureus be the one to do the actual complaining?

Are you the lawyer or agent of Aureus? Are you his father or brother or spouse? Or is this just an alt account of Aureus?

**Comment by ThomasThings** [comment]
One, Ad Hominem.

Two, I am not Aureus' lawyer or agent. I am not related to him by blood or marriage. I am simply a friend who doesn't like it when people take other people's things and give no credit to the original creator. I could ask the same of you. 

Three, let's imagine a hypothetical for a moment. Imagine you create a machine that could do something cool. Not world-changing, but cool. Now, imagine one day, someone comes by, and sees your machine. They decide they should have that. So, they take pictures of all of the blueprints, and make copies of the digital files, and they quickly print a new copy with their 3D printers, and they begin showing it off to everyone, neglecting to mention that they had no hand in creating it.
How would you feel then?

**Comment by XenoForce** [comment]
> *I could ask the same of you.*

You could, ...but you didn't.

> *How would you feel then?*

Well, I haven't actually lost anything. So, it is not the end of the world.

How would I feel if a friend jumps in, and starts fighting and arguing on my behalf?

Well, I would tell him to sit down, and mind his own business!

**Comment by ThomasThings** [comment]
Correct, I didn't ask you. Because it's irrelevant. Just like my relation to Aureus. 

And I did ask Aureus if he wanted me to do anything about it. And yes, he does. Because believe it or not, sometimes people don't like it when others take their things, and publish it under a different name. 

Another analogy: If someone wrote a book, and someone else copied your book, word for word, and published it under a slightly different name, how do you imagine that the original author would feel?

**Comment by XenoForce** [comment]
Hello Aureus!

**Comment by ThomasThings** [comment]
You're clearly not getting my point, or you're blatantly ignoring it. 

And for the record, no, I am not Aureus. As I've said, I'm just a friend who has a bit more free time, since I've recently stopped work on my own modding projects.

**Comment by XenoForce** [comment]
OK, here is my point: I don't want anything to stand in the way of this developer "ShardedFilms". This developer is doing good work, and I have been following this person for some time. Very impressive work.

I don't want trolls like you and/or Aureus to stand in his way, and/or trip him over, just over some stupid possessive licensing nonsense.

So, here is my question to Aureus: how can we free this developer up, so that his creative juices can flow, without hindrance??!!

Keep in mind that the whole Mindustry game is free and open source. So, trying to claim licensing on content developed for Mindustry, is a very, very long shot, seeing that all these mods use the API and infrastructure of the underlying game.

I know a thing or two about software licensing, and how hard it is to enforce, but I will stop here, for now, in order to give you a chance to respond.

**Comment by ThomasThings** [comment]
At this point it's clear to me beyond reasonable doubt that you're a troll, so I'm not even going to continue the conversation.
